apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
      - name: bookapi
        image: acrbookapi.azurecr.io/bookapi-minimal:latest
        ports:
        - containerPort: 80