apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookapi-chart.fullname" . }}
  namespace: bookapi
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "bookapi-chart.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080