name: Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  GITHUB_REPO_OWNER: mingfeiw
  GITHUB_REPO_NAME: bookapi-minimal
  GITHUB_BRANCH: master
  ACR_NAME: acrbookapi
  AKS_NAME: aks-bookapi-minimal
  RG_NAME: rg-bookapi-minimal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_REPO_OWNER }}/bookapi-minimal-infrastructure
          path: infra

      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_REPO_OWNER }}/${{ env.GITHUB_REPO_NAME }}
          ref: ${{ env.GITHUB_BRANCH }}
          path: src

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Dockerfile

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init
        
      - name: Terraform Import Resource Group
        working-directory: infra
        run: terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}

      - name: Terraform Import Other Resources
        working-directory: infra
        run: |
          terraform import azurerm_log_analytics_workspace.bookapi_workspace "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.OperationalInsights/workspaces/bookapi-law"
          terraform import azurerm_private_dns_zone.internal "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.Network/privateDnsZones/internal.local"
          terraform import azurerm_key_vault.bookapi_kv "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.KeyVault/vaults/kv-bookapiminimal"
          terraform import azurerm_container_registry.acr "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.ContainerRegistry/registries/acrbookapi"
          terraform import azurerm_network_security_group.nsg "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.Network/networkSecurityGroups/your-nsg-name"
          terraform import azurerm_storage_account.bookapi_sa "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.Storage/storageAccounts/stbookapiminimal"
          terraform import azurerm_virtual_network.vnet "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.Network/virtualNetworks/vnet-bookapi"
          terraform import azurerm_public_ip.appgw_pip "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RG_NAME }}/providers/Microsoft.Network/publicIPAddresses/pip-appgw-bookapi"

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: ACR login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build docker image
        run: |
          cd src
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/bookapi-minimal:latest .

      - name: Push docker image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/bookapi-minimal:latest

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.RG_NAME }} --name ${{ env.AKS_NAME }}

      - name: Deploy to AKS
        run: kubectl apply -f infra/k8s/